# Dataset Summary Report

### Day 7 Assignment

This notebook uses Python and Pandas to load, explore, and summarize a CSV dataset. It demonstrates dataset inspection, structure, data types, descriptive statistics, and identification of missing values.

In [1]:
import pandas as pd

In [2]:
from google.colab import files

uploaded = files.upload()

Saving Day7_Student_Dataset.csv to Day7_Student_Dataset.csv

In [3]:
df = pd.read_csv("Day7_Student_Dataset.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

## 1. Dataset Overview

In [4]:
df

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar
10,1011,Vivaan Kapoor,20,AI,91.0,94.0,Jaipur
11,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi
12,1013,Rahul Das,23,Data Science,72.0,81.0,Kolkata
13,1014,Sana Malik,18,AI,89.0,92.0,NaN
14,1015,Karan Joshi,20,Computer Science,77.0,85.0,Chandigarh
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

## 2. First Five Rows

In [5]:
df.head()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow

In [6]:
df.head(10)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar

## 3. Last Five Rows

In [7]:
df.tail()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

## 4. Random Sample of the Dataset

In [8]:
df.sample(5)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar
12,1013,Rahul Das,23,Data Science,72.0,81.0,Kolkata
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
13,1014,Sana Malik,18,AI,89.0,92.0,NaN

## 5. Dataset Shape

In [9]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Shape of dataset:", df.shape)

Number of rows: 25
Number of columns: 7
Shape of dataset: (25, 7)

## 6. Dataset Columns

In [10]:
print("Column names:")
print(df.columns)

Column names:
Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage',
       'City'],
      dtype='object')

In [11]:
print(list(df.columns))

['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage', 'City']

## 7. Dataset Index

In [12]:
print(df.index)

RangeIndex(start=0, stop=25, step=1)

## 8. Data Types

In [13]:
print(df.dtypes)

Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

## 9. Dataset Information

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

## 10. Descriptive Statistics

In [15]:
df.describe()

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

## 11. Missing Values

In [16]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

In [17]:
total_missing = df.isnull().sum().sum()

print("Total missing values:", total_missing)

Total missing values: 3

## 12. Duplicate Rows

In [18]:
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

In [19]:
print("Unique values in each column:")
print(df.nunique())

Unique values in each column:
Student_ID               25
Name                     25
Age                       6
Course                    3
Marks                    24
Attendance_Percentage    22
City                     13
dtype: int64

## 13. Basic Observations

- The dataset contains 25 rows representing individual records.
- The dataset contains 7 columns representing different features.
- The columns contain different data types such as int64,float64,object data.
- The `head()` and `tail()` functions were used to inspect the beginning and end of the dataset.
- Random samples were viewed using the `sample()` function.
- Descriptive statistics were generated using `describe()`.
- Missing values were checked using `isnull().sum()`.
- The dataset structure and data types were examined using `info()` and `dtypes`.

In [20]:
print("===== DATASET SUMMARY =====")

print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

print("\nColumns:")
print(list(df.columns))

print("\nData Types:")
print(df.dtypes)

print("\nTotal Missing Values:", df.isnull().sum().sum())

print("Duplicate Rows:", df.duplicated().sum())

===== DATASET SUMMARY =====
Number of Rows: 25
Number of Columns: 7

Columns:
['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage', 'City']

Data Types:
Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

Total Missing Values: 3
Duplicate Rows: 0